const likelihoods=[["A","Very Likely",5],["B","Likely",4],["C","Possible",3],["D","Unlikely",2],["E","Rare",1]];
["likelihood","rlikelihood"].forEach(id=>document.getElementById(id).innerHTML=likelihoods.map(x=>`<option value="${x[0]}">${x[0]} — ${x[1]}</option>`).join(""));
["impact","rimpact"].forEach(id=>document.getElementById(id).innerHTML=[1,2,3,4,5].map(x=>`<option value="${x}">${x}${x==5?" — Catastrophic":""}</option>`).join(""));
let risks=JSON.parse(localStorage.getItem("cudRisks")||"null")||[
 {id:"R-001",risk:"Failure to maintain accreditation requirements",category:"Compliance",owner:"IRP / Academic Affairs",effect:"Regulatory findings, reputational impact and program disruption.",cause:"Incomplete evidence, delayed actions or changing standards.",controls:"Accreditation calendar, document repository, internal review.",likelihood:"C",impact:5,treatment:"Mitigate",mitigation:"Quarterly compliance review and evidence tracking.",rlikelihood:"D",rimpact:4},
 {id:"R-002",risk:"Critical information system service interruption",category:"Technology",owner:"IT Department",effect:"Disruption to teaching, administration and reporting.",cause:"Infrastructure failure, cyber incident or vendor outage.",controls:"Backups, access controls, monitoring and recovery procedures.",likelihood:"C",impact:4,treatment:"Mitigate",mitigation:"Test recovery plan and strengthen redundancy.",rlikelihood:"D",rimpact:3},
 {id:"R-003",risk:"Decline in student retention",category:"Strategic",owner:"Student Success / Schools",effect:"Lower progression, revenue and student satisfaction.",cause:"Academic difficulty, engagement or service issues.",controls:"Advising, early alerts, surveys and intervention.",likelihood:"B",impact:3,treatment:"Mitigate",mitigation:"Program-level retention dashboard and targeted intervention.",rlikelihood:"C",rimpact:3}
];
function score(l,i){return (6-"ABCDE".indexOf(l)-1)*Number(i)}
function priority(l,i){let s=score(l,i);return s>=20?"Extreme":s>=12?"High":s>=6?"Medium":"Low"}
function save(){localStorage.setItem("cudRisks",JSON.stringify(risks));render()}
function render(){
 let q=document.getElementById("search").value.toLowerCase(), f=document.getElementById("filter").value;
 let data=risks.filter(r=>(!q||[r.id,r.risk,r.category,r.owner].join(" ").toLowerCase().includes(q))&&(!f||priority(r.likelihood,r.impact)==f));
 document.getElementById("rows").innerHTML=data.map(r=>{let i=risks.indexOf(r),p=priority(r.likelihood,r.impact),rp=priority(r.rlikelihood,r.rimpact);return `<tr><td><b>${r.id}</b></td><td style="min-width:260px">${r.risk}</td><td>${r.category}</td><td>${r.owner}</td><td><span class="pill p-${p}">${p}</span><br><small>${r.likelihood} × ${r.impact}</small></td><td>${r.treatment}</td><td><span class="pill p-${rp}">${rp}</span><br><small>${r.rlikelihood} × ${r.rimpact}</small></td><td><span class="action" onclick="editRisk(${i})">Edit</span> · <span class="action" onclick="removeRisk(${i})">Delete</span></td></tr>`}).join("");
 document.getElementById("total").textContent=risks.length;
 let ps=risks.map(r=>priority(r.likelihood,r.impact));document.getElementById("critical").textContent=ps.filter(x=>x=="High"||x=="Extreme").length;document.getElementById("medium").textContent=ps.filter(x=>x=="Medium").length;document.getElementById("low").textContent=ps.filter(x=>x=="Low").length;
 renderBars();renderHeat();
}
function renderBars(){let c={};risks.forEach(r=>c[r.category]=(c[r.category]||0)+1);let max=Math.max(1,...Object.values(c));document.getElementById("bars").innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="barrow"><span>${k}</span><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join("")||"<p>No risks yet.</p>"}
function renderHeat(){let h='<div class="axis">Impact →<br>Likelihood ↓</div>'+[1,2,3,4,5].map(x=>`<div class="axis">${x}</div>`).join("");likelihoods.forEach(L=>{h+=`<div class="axis">${L[0]}</div>`;[1,2,3,4,5].forEach(i=>{let p=priority(L[0],i),n=risks.filter(r=>r.likelihood==L[0]&&Number(r.impact)==i).length;h+=`<div class="cell hm-${p.toLowerCase()}">${n||""}<small>${p}</small></div>`})});document.getElementById("heatmap").innerHTML=h}
function openModal(){document.getElementById("riskForm").reset();document.getElementById("editIndex").value="";document.getElementById("modalTitle").textContent="Add New Risk";document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
function editRisk(i){openModal();let r=risks[i];document.getElementById("editIndex").value=i;document.getElementById("modalTitle").textContent="Edit Risk "+r.id;let map={riskId:"id",risk:"risk",category:"category",owner:"owner",effect:"effect",cause:"cause",controls:"controls",likelihood:"likelihood",impact:"impact",treatment:"treatment",mitigation:"mitigation",rlikelihood:"rlikelihood",rimpact:"rimpact"};Object.entries(map).forEach(([a,b])=>document.getElementById(a).value=r[b]??"")}
function removeRisk(i){if(confirm("Delete this risk?")){risks.splice(i,1);save()}}
document.getElementById("riskForm").onsubmit=e=>{e.preventDefault();let r={id:riskId.value,risk:risk.value,category:category.value,owner:owner.value,effect:effect.value,cause:cause.value,controls:controls.value,likelihood:likelihood.value,impact:+impact.value,treatment:treatment.value,mitigation:mitigation.value,rlikelihood:rlikelihood.value,rimpact:+rimpact.value};let i=editIndex.value;if(i==="")risks.unshift(r);else risks[+i]=r;save();closeModal()}
function exportCSV(){let keys=["id","risk","category","owner","effect","cause","controls","likelihood","impact","treatment","mitigation","rlikelihood","rimpact"];let rows=[["Risk ID","Risk","Category","Risk Owner","Likely Effect","Root Cause","Process Controls","Likelihood","Impact","Risk Treatment","Mitigation Plan","Revised Likelihood","Revised Impact","Risk Priority","Revised Risk Priority"]];risks.forEach(r=>rows.push([...keys.map(k=>r[k]),priority(r.likelihood,r.impact),priority(r.rlikelihood,r.rimpact)]));let csv=rows.map(a=>a.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="CUD_Risk_Register.csv";a.click()}
render();